# Site settings
title: John Redlich
email: jtredlich@gmail.com
description: Drupal Developer. Geek. Bearded Dad.
location: Long Island, NY
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://johnredli.ch" # the base hostname & protocol for your site
main_username: johntr
alt_username:  johntr10

#projects
projects:
  - title: ADC
    img: adc
    url: http://adctoday.com
    desc: Developed custom code features, drupal modules and site building tasks.
  - title: society for leadership
    img: nsls
    url: https://www.societyleadership.org/
    desc: Developed custom drupal modules, Data migrations and site building tasks.
  - title: HR Potenial Center
    img: hrpc
    url: http://hrpotenialcenter.com
    desc: Full Drupal 8 site, design and artitecture.
  - title: GCHA
    img: gcha
    url: http://www.greenlawncenterporthistorical.org/
    desc: Site buidling and design.
  - title: Retrofocus Eyeware
    img: retro
    url: https://www.retrofocuseyewear.com/
    desc: Store migration and site building.
  - title: RamSources
    img: ramsources
    url: https://github.com/johntr/RamSourcesAPI
    desc: Senior Project. Built Jenkins site, Modern PHP Rest Api backend and iOS app development.

#skills - image file needs to have same name as skill.
daily:
  - title: drupal
  - title: php
  - title: mariadb
  - title: git
often:
  - title: html
  - title: css
  - title: jquery
#education
educations:
  - title: Farmingdale State University of New York
    img: fsc
    desc: 2011-2016 BS Computer Programming and Information Systems

# Build settings
markdown: kramdown
